### ISSUE TITLE
'link_only' doesnt work

### ISSUE THREAD

**Issue by mamonu** [moj-analytical-services/sparklink#72]
when trying to link with setting `"link_type": "link_only"`

this code

`from sparklink import Sparklink
linker = Sparklink(settings, spark, df_l=persondf,df_r=censusdf,df=None)`

gives 

ValueError: For link_type = 'link_only', you must pass two Spark dataframes to Sparklink using the df_l and df_r argument. The df argument should be omitted or set to None. e.g. linker = Sparklink(settings, spark, df_l=my_first_df, df_r=df_to_link_to_first_one)

**Comment by samnlindsay** [comment]
PR #73 allows `_check_args` to pass, but the unit tests need to include this to make sure such issues are caught in future releases. Likely to become a wider issue when test use a different workflow to "real" users.
